---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: vagrant
  provider:
    name: vbox
platforms:
  - name: podman
    box: centos/8
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATHS: ./.cache/collections 
verifier:
  name: ansible
