---
dependency:
  name: galaxy
  options:
    requirements-file: ./requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: vagrant
  provider:
    name: vbox
platforms:
  - name: podman
    box: centos/8
provisioner:
  name: ansible
verifier:
  name: ansible
